function F = SolutionMeasures_SHE357_dHdk_0_dHdkk_0(~,uu,p,mesh_params)
  
mu = p(1);
a = p(2); 
b  = p(3);
sigma = p(4);
% k  = p(5);

  % Auxiliary variables
  n = mesh_params.nz;
  u = uu(1:n);
  uk = uu(1+n:2*n);
  ukk = uu(2*n+1:3*n); 
  c1 = uu(3*n+1);
  c2 = uu(3*n+2);
  c3 = uu(3*n+3); 
  b  = uu(3*n+4);
  k = uu(3*n+5); 
  
  w = mesh_params.wz;
  D2z = mesh_params.D2z;
  Dz = mesh_params.Dz;

  I = speye(n);
  % E = w*(0.5*((I + k^2*D2z)*u).^2 - 0.5*mu*u.^2 - nu*u.^3/3 + g*u.^4/4);
  E = w*((D2z*u).^2 - sigma*(Dz*u).^2/2 - 0.5*mu*u.^2 + a*u.^4/4 - b*u.^6/6 + u.^8/8);
  H = -0.5*k^4*(D2z*u).^2 + sigma*k^2*(Dz*u).^2/2 + (1-mu)*u.^2/2  ...
      + 1/4*a*u.^4 - b*u.^6/6 + u.^8/8 + k^4*(Dz*u).*(Dz*D2z*u);
  A = mean(sigma*k*(Dz*u).^2 - 2*k^3*(D2z*u).^2);

  Ak= mean(sigma*(Dz*u).^2 + 2*sigma*k.*(Dz*u).*(Dz*uk) ...
      - 6*k^2*(D2z*u).^2 - 4*k.^3*(D2z*u).*(D2z*uk));

  Akk = mean(2*sigma*(Dz*u).*(Dz*uk) + ...
      2*sigma.*(Dz*u).*(Dz*uk) + 2*sigma*k.*((Dz*uk).^2 + (Dz*u).*(Dz*ukk)) ... 
      - 12*k*(D2z*u).^2 - 12*k.^2*(D2z*u).*(D2z*uk) ... 
      - 12*k.^2*(D2z*u).*(D2z*uk) - 4*k.^3.*((D2z*uk).*(D2z*uk) + (D2z*u).*(D2z*ukk))); 

dHdk = -2*k^3*(D2z*u).^2 -k^4*(D2z*u).*(D2z*uk) ...
    + sigma*k*(Dz*u).^2 + sigma*k^2*(Dz*u).*(Dz*uk) ...
    + (1-mu)*u.*uk + a*u.^3.*uk - b*u.^5.*uk + u.^7.*uk ...
    + 4*k^3*(Dz*u).*(Dz*D2z*u) + k^4*(Dz*uk).*(Dz*D2z*u) ...
    + k^4*(Dz*u).*(Dz*D2z*uk);

dHdkk = ...
    -6*k^2.*(D2z*u).^2 ...
    -8*k^3.*(D2z*u).*(D2z*uk) ...
    - k^4.*((D2z*uk).^2 + (D2z*u).*(D2z*ukk)) ...
    + sigma.*(Dz*u).^2 + 4*sigma.*k.*(Dz*u).*(Dz*uk) + sigma.*k^2.*((Dz*uk).^2 + (Dz*u).*(Dz*ukk)) ...
    + (1-mu).*( uk.^2 + u.*ukk ) ...
    + a.*( 3*u.^2.*uk.^2 + u.^3.*ukk ) ...
    - b.*( 5*u.^4.*uk.^2 + u.^5.*ukk ) ...
    + ( 7*u.^6.*uk.^2 + u.^7.*ukk ) ...
    + 12*k^2.*(Dz*u).*(Dz*D2z*u) ...
    + 8*k^3.*(Dz*uk).*(Dz*D2z*u) ...
    + 8*k^3.*(Dz*u).*(Dz*D2z*uk) ...
    + k^4.*( (Dz*ukk).*(Dz*D2z*u) + 2*(Dz*uk).*(Dz*D2z*uk) + (Dz*u).*(Dz*D2z*ukk) );


  F = [mesh_params.wz*(u.^2)/mesh_params.Lz, E, H(1), A, mean(dHdk),mean(dHdkk),b,k,Ak,Akk];

end
